theme = "fleet_dark"

[editor]
true-color = true
text-width = 80

[editor.soft-wrap]
enable = true

[editor.cursor-shape]
insert = "bar"

[editor.lsp]
display-messages = true
# display-inlay-hints = true

[keys.normal]
X = "extend_line_above"
A-k = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]
A-j = ["extend_to_line_bounds", "delete_selection", "paste_after"]
C-f = [":new", ":insert-output lf-pick", "select_all", "split_selection_on_newline", "goto_file", "goto_last_modified_file", ":buffer-close!", ":theme fleet_dark"]


[keys.normal.space]
q = ":quit"
w = ":write"
m = ":format"
M = ":sh prettier --write ."

[keys.insert]
C-h = "move_char_left"
C-j = "move_line_down"
C-k = "move_line_up"
C-l = "move_char_right"

[keys.normal.space.";"]
g = ":sh zellij action new-tab -l lg"
s = ":sh zellij run -fc -- lazygit"


